### ISSUE TITLE
Question about AQMAR corpus canonical splits

### ISSUE THREAD

**Issue by Mostafa-Samir** [stanfordnlp/stanza-train#2]
Hello,

I'm trying to re-produce the results reported in the paper about Arabic NER on AQMAR corpus. It's mentioned that the canonical splits for AQMAR is used, however there is only dev/testing splits in the original AQMAR corpus, no training split. Did you use that split for training (e.g. testing --> training, dev --> testing) or is there another split used?

Thanks

**Comment by yuhaozhang** [comment]
Hi @Mostafa-Samir, we split the AQMAR corpus in the same way as the Arabic NER challenge does (https://www.topcoder.com/challenges/30087004). You can find the details in the linked page, but in short, the dataset is split according to the topics such that there is no overlapping topics in each split. We found this to be used in several Arabic NER papers.

Since the original AQMAR corpus is freely available, I've put a version that we used at this link: https://drive.google.com/file/d/1wWMdffANjpudROrsa6iRHpSwEkaUboVI/view?usp=sharing
